const idiomas = {
  es: {
    inicio: '🏠 Inicio', grupo: '👥 Grupo', bots: '🤖 Bots', seguridad: '🛡️ Seguridad', ajustes: '⚙️ Ajustes', extras: '🎁 Extras', ia: '🧠 IA', redes: '🌐 Redes', ayuda: '❓ Ayuda', lema: 'Una Familia · Un Bot · Sin Límites', seleccionar: 'Selecciona una opción:', ajustesTitulo: '⚙️ Ajustes de {bot}', antilink: '🛡️ Antilink', activado: 'Activado', desactivado: 'Desactivado', idioma: '🌐 Idioma', prefijo: '🔤 Prefijo', seguridadTitulo: '🛡️ Panel de Seguridad', idiomaGrupo: '🌐 Idioma del grupo', idiomaActual: 'Idioma actual: {language}', seleccionarIdioma: 'Selecciona el idioma:', espanol: '🇪🇸 Español', ingles: '🇺🇸 English', prefijoTitulo: '🔤 Prefijo de comandos', prefijoActual: 'Prefijo actual: {prefix}', prefijoAyuda: 'Para cambiarlo usa:\n/prefijo !\n/prefijo .\n/prefijo /', soloGrupos: 'ℹ️ Los ajustes de grupo solo están disponibles en grupos.', soloAdmins: '⛔ Solo los administradores pueden modificar los ajustes.', usoIdioma: 'Uso: /idioma es|en', idiomaActualizado: '🌐 Idioma actualizado: {language}', usoPrefijo: 'Uso: /prefijo !', prefijoGuardado: '🔤 Prefijo guardado: {prefix}', seguridadInfo: 'Permisos del bot: {botAdmin}', admin: 'Administrador', noAdmin: 'No soy administrador', seguridadUso: 'Usa /antilink on|off para cambiarlo.', soloGrupoSeguridad: 'ℹ️ El panel de seguridad solo está disponible en grupos.', antilinkUso: 'Uso: /antilink on|off', antilinkActivado: '🛡️ Antilink activado ✅', antilinkDesactivado: '🛡️ Antilink desactivado ❌', linksNo: '🚫 @{user}, los links no están permitidos aquí.', estadoTitulo: '🤖 {bot} — Estado del Sistema', estado: 'Estado', online: 'Online 24/7', uptime: 'Uptime', ram: 'RAM usada', plataforma: 'Plataforma', node: 'Node', iaTitulo: '🧠 Asistente IA', iaUso: 'Usa: `/ia tu pregunta`', iaEjemplo: 'Ejemplo: `/ia explícame qué es la fotosíntesis`', resetia: '/resetia — Borra tu historial de conversación', iaFaltaKey: '⚠️ Falta configurar ANTHROPIC_API_KEY en tu archivo .env', iaPregunta: '✍️ Escribe tu pregunta después del comando.\nEjemplo: /ia ¿Cuál es la capital de Francia?', iaPensando: '🤖 Pensando...', iaSinRespuesta: '🤷 No obtuve respuesta de la IA.', iaError: '❌ Ocurrió un error al consultar la IA.', iaHistorialBorrado: '🧹 Se borró tu historial de conversación con la IA.', actualizar: 'Actualizar', noDisponible: 'No disponible', nombre: 'Nombre', sinNombre: 'Sin nombre', id: 'ID', username: 'Username', miembros: 'Miembros', administradores: 'Administradores', botAdministrador: 'Bot administrador', si: 'Sí', no: 'No', grupoError: 'No pude obtener la información del grupo. Revisa los permisos del bot.'
  },
  en: {
    inicio: '🏠 Home', grupo: '👥 Group', bots: '🤖 Bots', seguridad: '🛡️ Security', ajustes: '⚙️ Settings', extras: '🎁 Extras', ia: '🧠 AI', redes: '🌐 Social', ayuda: '❓ Help', lema: 'One Family · One Bot · No Limits', seleccionar: 'Select an option:', ajustesTitulo: '⚙️ {bot} Settings', antilink: '🛡️ Antilink', activado: 'Enabled', desactivado: 'Disabled', idioma: '🌐 Language', prefijo: '🔤 Prefix', seguridadTitulo: '🛡️ Security Panel', idiomaGrupo: '🌐 Group language', idiomaActual: 'Current language: {language}', seleccionarIdioma: 'Select the language:', espanol: '🇪🇸 Spanish', ingles: '🇺🇸 English', prefijoTitulo: '🔤 Command prefix', prefijoActual: 'Current prefix: {prefix}', prefijoAyuda: 'To change it use:\n/prefijo !\n/prefijo .\n/prefijo /', soloGrupos: 'ℹ️ Group settings are only available in groups.', soloAdmins: '⛔ Only administrators can modify settings.', usoIdioma: 'Usage: /idioma es|en', idiomaActualizado: '🌐 Language updated: {language}', usoPrefijo: 'Usage: /prefijo !', prefijoGuardado: '🔤 Prefix saved: {prefix}', seguridadInfo: 'Bot permissions: {botAdmin}', admin: 'Administrator', noAdmin: 'Not an administrator', seguridadUso: 'Use /antilink on|off to change it.', soloGrupoSeguridad: 'ℹ️ The security panel is only available in groups.', antilinkUso: 'Usage: /antilink on|off', antilinkActivado: '🛡️ Antilink enabled ✅', antilinkDesactivado: '🛡️ Antilink disabled ❌', linksNo: '🚫 @{user}, links are not allowed here.', estadoTitulo: '🤖 {bot} — System Status', estado: 'Status', online: 'Online 24/7', uptime: 'Uptime', ram: 'Used RAM', plataforma: 'Platform', node: 'Node', iaTitulo: '🧠 AI Assistant', iaUso: 'Use: `/ia your question`', iaEjemplo: 'Example: `/ia explain photosynthesis to me`', resetia: '/resetia — Clear your conversation history', iaFaltaKey: '⚠️ ANTHROPIC_API_KEY is missing from your .env file', iaPregunta: '✍️ Write your question after the command.\nExample: /ia What is the capital of France?', iaPensando: '🤖 Thinking...', iaSinRespuesta: '🤷 I did not get a response from the AI.', iaError: '❌ An error occurred while querying the AI.', iaHistorialBorrado: '🧹 Your AI conversation history has been cleared.', actualizar: 'Refresh', noDisponible: 'Not available', nombre: 'Name', sinNombre: 'Unnamed', id: 'ID', username: 'Username', miembros: 'Members', administradores: 'Administrators', botAdministrador: 'Bot administrator', si: 'Yes', no: 'No', grupoError: 'I could not get the group information. Check the bot permissions.'
  }
};

function obtenerIdioma(grupo) {
  return idiomas[grupo?.language] ? grupo.language : 'es';
}

function t(grupo, clave, variables = {}) {
  const idioma = obtenerIdioma(grupo);
  let texto = idiomas[idioma][clave] || idiomas.es[clave] || clave;
  for (const [nombre, valor] of Object.entries(variables)) texto = texto.replaceAll(`{${nombre}}`, String(valor));
  return texto;
}

module.exports = { t, obtenerIdioma };
